# Generated by Django 6.0.7 on 2026-07-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('grupo', models.CharField(blank=True, max_length=100, verbose_name='Grupo')),
                ('subgrupo', models.CharField(blank=True, max_length=100, verbose_name='Subgrupo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['tipo', 'orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de catálogo',
                'verbose_name_plural': 'Tipos de catálogos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('destino_egreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_destino', to='pacientes.catalogo', verbose_name='Destino al egreso')),
                ('insuficiencia_respiratoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_ir', to='pacientes.catalogo', verbose_name='Insuficiencia respiratoria')),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_procedencia', to='pacientes.catalogo', verbose_name='Procedencia')),
            ],
            options={
                'verbose_name': 'Internación',
                'verbose_name_plural': 'Internaciones',
                'ordering': ['-fecha_ingreso', 'paciente'],
            },
        ),
        migrations.CreateModel(
            name='InternacionSoporteRespiratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes_respiratorios', to='pacientes.internacion', verbose_name='Internación')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_soporte', to='pacientes.catalogo', verbose_name='Soporte respiratorio')),
            ],
            options={
                'verbose_name': 'Soporte respiratorio',
                'verbose_name_plural': 'Soportes respiratorios',
                'ordering': ['internacion', 'fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='InternacionTratamientoAntimicrobiano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('antimicrobiano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_antimicrobianos', to='pacientes.catalogo', verbose_name='Antimicrobiano')),
                ('indicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_antimicrobianos', to='pacientes.catalogo', verbose_name='Indicación')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_antimicrobianos', to='pacientes.internacion', verbose_name='Internación')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vias_antimicrobianos', to='pacientes.catalogo', verbose_name='Vía de administración')),
            ],
            options={
                'verbose_name': 'Tratamiento antimicrobiano',
                'verbose_name_plural': 'Tratamientos antimicrobianos',
                'ordering': ['internacion', 'fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='MuestraMicrobiologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_toma', models.DateField(verbose_name='Fecha de toma')),
                ('resultado', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo'), ('C', 'Contaminado'), ('PE', 'Pendiente')], default='PE', max_length=2, verbose_name='Resultado')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_microbiologicas', to='pacientes.internacion', verbose_name='Internación')),
                ('tipo_muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_tipo', to='pacientes.catalogo', verbose_name='Tipo de muestra')),
            ],
            options={
                'verbose_name': 'Muestra microbiológica',
                'verbose_name_plural': 'Muestras microbiológicas',
                'ordering': ['-fecha_toma'],
            },
        ),
        migrations.CreateModel(
            name='AislamientoMicrobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('significativo', models.BooleanField(default=True, verbose_name='Significativo')),
                ('germen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aislamientos_germen', to='pacientes.catalogo', verbose_name='Germen')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aislamientos', to='pacientes.muestramicrobiologica', verbose_name='Muestra')),
            ],
            options={
                'verbose_name': 'Aislamiento microbiológico',
                'verbose_name_plural': 'Aislamientos microbiológicos',
                'ordering': ['muestra', 'germen'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('numero_afiliado', models.CharField(blank=True, max_length=50, verbose_name='Número de afiliado')),
                ('estado_vital', models.CharField(choices=[('A', 'Activo'), ('F', 'Fallecido')], default='A', max_length=1, verbose_name='Estado vital')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_cobertura', to='pacientes.catalogo', verbose_name='Cobertura')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_tipo_documento', to='pacientes.catalogo', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='internacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internaciones', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.CreateModel(
            name='RecorridoInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='pacientes.internacion', verbose_name='Internación')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_sector', to='pacientes.catalogo', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Recorrido de internación',
                'verbose_name_plural': 'Recorridos de internación',
                'ordering': ['internacion', 'orden', 'fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='SensibilidadMicrobiologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('S', 'Sensible'), ('I', 'Intermedio'), ('R', 'Resistente')], max_length=1, verbose_name='Resultado')),
                ('aislamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensibilidades', to='pacientes.aislamientomicrobiologico', verbose_name='Aislamiento')),
                ('antibiotico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensibilidades_antibiotico', to='pacientes.catalogo', verbose_name='Antibiótico')),
            ],
            options={
                'verbose_name': 'Sensibilidad microbiológica',
                'verbose_name_plural': 'Sensibilidades microbiológicas',
                'ordering': ['aislamiento', 'antibiotico'],
            },
        ),
        migrations.AddField(
            model_name='catalogo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pacientes.tipocatalogo', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='InternacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internaciones', to='pacientes.catalogo', verbose_name='Catálogo')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='pacientes.internacion', verbose_name='Internación')),
            ],
            options={
                'verbose_name': 'Elemento de la internación',
                'verbose_name_plural': 'Elementos de la internación',
                'ordering': ['internacion', 'catalogo'],
                'indexes': [models.Index(fields=['internacion'], name='pacientes_i_interna_2eb933_idx'), models.Index(fields=['catalogo'], name='pacientes_i_catalog_af23a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('internacion', 'catalogo'), name='uk_internacion_catalogo')],
            },
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='uk_paciente_tipo_numero_documento'),
        ),
        migrations.AddConstraint(
            model_name='catalogo',
            constraint=models.UniqueConstraint(fields=('tipo', 'codigo'), name='uk_catalogo_tipo_codigo'),
        ),
    ]
