# Generated by Django 6.0.7 on 2026-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocatalogo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de catálogo', 'verbose_name_plural': 'Tipos de catálogos'},
        ),
        migrations.AddField(
            model_name='tipocatalogo',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='tipocatalogo',
            name='protegido',
            field=models.BooleanField(default=False, help_text='Impide modificaciones desde la administración funcional.', verbose_name='Protegido'),
        ),
    ]
