# Generated by Django 6.0.7 on 2026-07-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_cargar_catalogos_basicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_vital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_estado_vital', to='pacientes.catalogo', verbose_name='Estado vital'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_sexo', to='pacientes.catalogo', verbose_name='Sexo'),
        ),
    ]
