# Generated by Django 6.0.7 on 2026-07-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_cargar_catalogos_internacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestramicrobiologica',
            name='mtb_detectado',
            field=models.CharField(blank=True, choices=[('D', 'Detectado'), ('ND', 'No detectado'), ('I', 'Indeterminado')], max_length=2, null=True, verbose_name='Mycobacterium tuberculosis detectada (GeneXpert)'),
        ),
        migrations.AddField(
            model_name='muestramicrobiologica',
            name='resistencia_rifampicina',
            field=models.CharField(blank=True, choices=[('D', 'Detectado'), ('ND', 'No detectado'), ('I', 'Indeterminado')], max_length=2, null=True, verbose_name='Resistencia a rifampicina (GeneXpert)'),
        ),
        migrations.AlterField(
            model_name='aislamientomicrobiologico',
            name='germen',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'GERMEN'}, on_delete=django.db.models.deletion.PROTECT, related_name='aislamientos_germen', to='pacientes.catalogo', verbose_name='Germen'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='destino_egreso',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__codigo': 'DESTINO_EGRESO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_destino', to='pacientes.catalogo', verbose_name='Destino al egreso'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='insuficiencia_respiratoria',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__codigo': 'TIPO_IR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_ir', to='pacientes.catalogo', verbose_name='Insuficiencia respiratoria'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='procedencia',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'PROCEDENCIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_procedencia', to='pacientes.catalogo', verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='internacionsoporterespiratorio',
            name='soporte',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'SOPORTE_RESPIRATORIO'}, on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_soporte', to='pacientes.catalogo', verbose_name='Soporte respiratorio'),
        ),
        migrations.AlterField(
            model_name='internaciontratamientoantimicrobiano',
            name='antimicrobiano',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'ANTIMICROBIANO'}, on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_antimicrobianos', to='pacientes.catalogo', verbose_name='Antimicrobiano'),
        ),
        migrations.AlterField(
            model_name='internaciontratamientoantimicrobiano',
            name='indicacion',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'INDICACION_ATB'}, on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_antimicrobianos', to='pacientes.catalogo', verbose_name='Indicación'),
        ),
        migrations.AlterField(
            model_name='internaciontratamientoantimicrobiano',
            name='via',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'VIA_ADMINISTRACION'}, on_delete=django.db.models.deletion.PROTECT, related_name='vias_antimicrobianos', to='pacientes.catalogo', verbose_name='Vía de administración'),
        ),
        migrations.AlterField(
            model_name='muestramicrobiologica',
            name='tipo_muestra',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'TIPO_MUESTRA'}, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_tipo', to='pacientes.catalogo', verbose_name='Tipo de muestra'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cobertura',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'COBERTURA'}, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_cobertura', to='pacientes.catalogo', verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_vital',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'ESTADO_VITAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_estado_vital', to='pacientes.catalogo', verbose_name='Estado vital'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'SEXO'}, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_sexo', to='pacientes.catalogo', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_documento',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'TIPO_DOCUMENTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_tipo_documento', to='pacientes.catalogo', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='recorridointernacion',
            name='sector',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'SECTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_sector', to='pacientes.catalogo', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='sensibilidadmicrobiologica',
            name='antibiotico',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'ANTIMICROBIANO'}, on_delete=django.db.models.deletion.PROTECT, related_name='sensibilidades_antibiotico', to='pacientes.catalogo', verbose_name='Antibiótico'),
        ),
    ]
