# Generated by Django 6.0.7 on 2026-07-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0022_alter_aislamientomicrobiologico_germen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorridointernacion',
            name='internacion',
        ),
        migrations.RemoveField(
            model_name='recorridointernacion',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='internacion',
            name='antecedentes_respiratorios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'ANTECEDENTE_RESPIRATORIO'}, related_name='+', to='pacientes.catalogo', verbose_name='Antecedentes respiratorios'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='exposicion_pasiva',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'EXPOSICION_PASIVA'}, related_name='+', to='pacientes.catalogo', verbose_name='Exposición pasiva al humo de tabaco'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='exposiciones_laborales',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'EXPOSICION_LABORAL'}, related_name='+', to='pacientes.catalogo', verbose_name='Exposiciones laborales y ambientales'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_infeccioso',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_INFECCIOSO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Motivo infeccioso'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_intersticial',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_INTERSTICIAL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Motivo intersticial'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_obstructivo',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_OBSTRUCTIVO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Motivo obstructivo'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_oncologico',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_ONCOLOGICO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Motivo oncológico'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_otro',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_OTRO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Otro motivo'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_pleural',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_PLEURAL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Motivo pleural'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_vascular',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_VASCULAR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Motivo vascular'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_infecciosos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_INFECCIOSO'}, related_name='+', to='pacientes.catalogo', verbose_name='Motivos infecciosos'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_intersticiales',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_INTERSTICIAL'}, related_name='+', to='pacientes.catalogo', verbose_name='Motivos intersticiales'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_obstructivos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_OBSTRUCTIVO'}, related_name='+', to='pacientes.catalogo', verbose_name='Motivos obstructivos'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_oncologicos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_ONCOLOGICO'}, related_name='+', to='pacientes.catalogo', verbose_name='Motivos oncológicos'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_otros',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_OTRO'}, related_name='+', to='pacientes.catalogo', verbose_name='Otros motivos'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_pleurales',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_PLEURAL'}, related_name='+', to='pacientes.catalogo', verbose_name='Motivos pleurales'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivos_vasculares',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'MOTIVO_VASCULAR'}, related_name='+', to='pacientes.catalogo', verbose_name='Motivos vasculares'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='otros_habitos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'HABITO_INHALATORIO'}, related_name='+', to='pacientes.catalogo', verbose_name='Otros hábitos inhalatorios'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='soporte_respiratorio',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'SOPORTE_RESPIRATORIO'}, related_name='+', to='pacientes.catalogo', verbose_name='Soporte respiratorio'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='tabaquismo',
            field=models.CharField(blank=True, choices=[('NUNCA', 'Nunca fumó'), ('ACTIVO', 'Fumador activo'), ('EXFUMADOR', 'Exfumador')], max_length=20, verbose_name='Tabaquismo'),
        ),
        migrations.DeleteModel(
            name='InternacionSoporteRespiratorio',
        ),
        migrations.DeleteModel(
            name='RecorridoInternacion',
        ),
    ]
