# Generated by Django 6.0.7 on 2026-07-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0023_remove_recorridointernacion_internacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_infecciosos',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_intersticiales',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_obstructivos',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_oncologicos',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_otros',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_pleurales',
        ),
        migrations.RemoveField(
            model_name='internacion',
            name='motivos_vasculares',
        ),
    ]
