# Generated by Django 6.0.7 on 2026-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0024_remove_internacion_motivos_infecciosos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='anos_fumando',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Años fumando'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='cigarrillos_por_dia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cigarrillos por día'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='indice_paquetes_anio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Índice paquetes-año'),
        ),
    ]
