# Generated by Django 6.0.7 on 2026-07-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0025_internacion_anos_fumando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestramicrobiologica',
            name='destino',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'DESTINO_MUESTRA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_destino', to='pacientes.catalogo', verbose_name='Destino'),
        ),
    ]
