# Generated by Django 6.0.7 on 2026-07-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0027_cargar_destino_muestra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aislamientomicrobiologico',
            options={'ordering': ['estudio', 'germen'], 'verbose_name': 'Aislamiento microbiológico', 'verbose_name_plural': 'Aislamientos microbiológicos'},
        ),
        migrations.RemoveField(
            model_name='aislamientomicrobiologico',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='muestramicrobiologica',
            name='mtb_detectado',
        ),
        migrations.RemoveField(
            model_name='muestramicrobiologica',
            name='resistencia_rifampicina',
        ),
        migrations.CreateModel(
            name='EstudioMicrobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('IN', 'Informado')], default='PE', max_length=2, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='pacientes.muestramicrobiologica', verbose_name='Muestra')),
                ('tipo_estudio', models.ForeignKey(limit_choices_to={'activo': True, 'tipo__codigo': 'TIPO_ESTUDIO_MICROBIOLOGICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='estudios_microbiologicos', to='pacientes.catalogo', verbose_name='Tipo de estudio')),
            ],
            options={
                'verbose_name': 'Estudio microbiológico',
                'verbose_name_plural': 'Estudios microbiológicos',
                'ordering': ['muestra', 'tipo_estudio'],
            },
        ),
        migrations.CreateModel(
            name='CultivoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_cultivo', models.CharField(choices=[('BAC', 'Bacteriología'), ('MTB', 'Micobacterias'), ('MIC', 'Micología')], max_length=3, verbose_name='Tipo de cultivo')),
                ('resultado', models.CharField(choices=[('CUR', 'En curso'), ('SD', 'Sin desarrollo'), ('POS', 'Positivo'), ('POL', 'Polimicrobiano'), ('CON', 'Contaminado'), ('MNA', 'Muestra no apta')], max_length=3, verbose_name='Resultado')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha del informe')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cultivo', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de cultivo',
                'verbose_name_plural': 'Detalles de cultivo',
            },
        ),
        migrations.CreateModel(
            name='BetaDGlucanoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo'), ('IND', 'Indeterminado')], max_length=3, verbose_name='Resultado')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha del informe')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beta_d_glucano', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de Beta-D-glucano',
                'verbose_name_plural': 'Detalles de Beta-D-glucano',
            },
        ),
        migrations.CreateModel(
            name='BaciloscopiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('POS', 'Positiva'), ('NEG', 'Negativa'), ('NR', 'No realizada')], max_length=3, verbose_name='Resultado')),
                ('graduacion', models.CharField(blank=True, choices=[('+', '+'), ('++', '++'), ('+++', '+++')], max_length=3, verbose_name='Graduación')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baciloscopia', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de baciloscopía',
                'verbose_name_plural': 'Detalles de baciloscopía',
            },
        ),
        migrations.CreateModel(
            name='AnatomiaPatologicaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo')], max_length=3, verbose_name='Resultado')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha del informe')),
                ('germen', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'GERMEN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anatomia_patologica_germen', to='pacientes.catalogo', verbose_name='Germen identificado')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anatomia_patologica', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de anatomía patológica',
                'verbose_name_plural': 'Detalles de anatomía patológica',
            },
        ),
        migrations.AddField(
            model_name='aislamientomicrobiologico',
            name='estudio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='aislamientos', to='pacientes.estudiomicrobiologico', verbose_name='Estudio microbiológico'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GalactomananoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo'), ('IND', 'Indeterminado')], max_length=3, verbose_name='Resultado')),
                ('indice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Índice')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='galactomanano', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de galactomanano',
                'verbose_name_plural': 'Detalles de galactomanano',
            },
        ),
        migrations.CreateModel(
            name='GeneXpertDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('mtb_detectado', models.CharField(choices=[('D', 'Detectado'), ('ND', 'No detectado'), ('I', 'Indeterminado')], max_length=2, verbose_name='Mycobacterium tuberculosis')),
                ('resistencia_rifampicina', models.CharField(blank=True, choices=[('D', 'Detectado'), ('ND', 'No detectado'), ('I', 'Indeterminado')], max_length=2, null=True, verbose_name='Resistencia a rifampicina')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genexpert', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle GeneXpert',
                'verbose_name_plural': 'Detalles GeneXpert',
            },
        ),
        migrations.CreateModel(
            name='InmunodifusionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo'), ('IND', 'Indeterminado')], max_length=3, verbose_name='Resultado')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha del informe')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inmunodifusion', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de inmunodifusión',
                'verbose_name_plural': 'Detalles de inmunodifusión',
            },
        ),
        migrations.CreateModel(
            name='PanelViralDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_viral', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle panel viral',
                'verbose_name_plural': 'Detalles panel viral',
            },
        ),
        migrations.CreateModel(
            name='PneumocystisDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('resultado', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo'), ('IND', 'Indeterminado')], max_length=3, verbose_name='Resultado')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha del informe')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pneumocystis', to='pacientes.estudiomicrobiologico', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Detalle de Pneumocystis',
                'verbose_name_plural': 'Detalles de Pneumocystis',
            },
        ),
        migrations.CreateModel(
            name='VirusDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virus_detectados', to='pacientes.panelviraldetalle', verbose_name='Panel viral')),
                ('virus', models.ForeignKey(limit_choices_to={'activo': True, 'tipo__codigo': 'VIRUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='virus_panel', to='pacientes.catalogo', verbose_name='Virus')),
            ],
            options={
                'verbose_name': 'Virus detectado',
                'verbose_name_plural': 'Virus detectados',
            },
        ),
        migrations.AddConstraint(
            model_name='estudiomicrobiologico',
            constraint=models.UniqueConstraint(fields=('muestra', 'tipo_estudio'), name='uk_muestra_tipo_estudio'),
        ),
    ]
