# Generated by Django 6.0.7 on 2026-07-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0029_recuperar_catalogos_internacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internacion',
            old_name='exposicion_pasiva',
            new_name='tabaquismo_pasivo',
        ),
        migrations.RenameField(
            model_name='internacion',
            old_name='otros_habitos',
            new_name='otros_habitos_inhalatorios',
        ),
    ]