# Generated by Django 6.0.7 on 2026-07-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0031_cargar_catalogos_exposicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internacion',
            options={'verbose_name': 'Internación', 'verbose_name_plural': 'Internaciones'},
        ),
        migrations.AddField(
            model_name='internacion',
            name='exposiciones_ambientales',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'EXPOSICION_AMBIENTAL'}, related_name='+', to='pacientes.catalogo', verbose_name='Exposiciones ambientales'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='exposiciones_laborales',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo__in': ['EXPOSICION_LABORAL', 'EXPOSICION_OCUPACIONAL']}, related_name='+', to='pacientes.catalogo', verbose_name='Exposiciones laborales'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='motivo_otro',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo__codigo__in': ['MOTIVO_OTRO', 'MOTIVO_OTROS']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.catalogo', verbose_name='Otro motivo'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='otros_habitos_inhalatorios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'OTROS_HABITOS_INHALATORIOS'}, related_name='+', to='pacientes.catalogo', verbose_name='Otros hábitos inhalatorios'),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='tabaquismo_pasivo',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'TABAQUISMO_PASIVO'}, related_name='+', to='pacientes.catalogo', verbose_name='Tabaquismo pasivo'),
        ),
    ]
