# Generated by Django 6.0.7 on 2026-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0032_alter_internacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='vacuna_neumococo_fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha/Año vacuna Neumococo'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='vacuna_vsr_fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha/Año vacuna VSR'),
        ),
    ]
