# Generated by Django 6.0.7 on 2026-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0033_internacion_vacuna_neumococo_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacioncatalogo',
            name='observacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha / Observación'),
        ),
    ]
