# Generated by Django 6.0.7 on 2026-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0034_internacioncatalogo_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aislamientomicrobiologico',
            name='significativo',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='tipo_microorganismo',
            field=models.CharField(blank=True, choices=[('bacteria', 'Bacteria'), ('hongo', 'Hongo'), ('virus', 'Virus'), ('parasito', 'Parásito'), ('otro', 'Otro')], help_text="Solo para ítems de tipo 'Germen'", max_length=20, null=True, verbose_name='Tipo de microorganismo'),
        ),
    ]
