# Generated by Django 6.0.7 on 2026-08-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0035_remove_aislamientomicrobiologico_significativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(verbose_name='Fecha del estudio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('hallazgos', models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'HALLAZGO_TOMOGRAFICO'}, related_name='tomografias_hallazgos', to='pacientes.catalogo', verbose_name='Hallazgos')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomografias', to='pacientes.internacion', verbose_name='Internación')),
                ('tipo', models.ForeignKey(limit_choices_to={'activo': True, 'tipo__codigo': 'TIPO_TOMOGRAFIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='tomografias_tipo', to='pacientes.catalogo', verbose_name='Tipo de tomografía')),
            ],
            options={
                'verbose_name': 'Tomografía',
                'verbose_name_plural': 'Tomografías',
                'ordering': ['-fecha'],
            },
        ),
    ]
