# Generated by Django 6.0.7 on 2026-08-13 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0036_tomografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomografia',
            name='hallazgos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo__in': ['HALLAZGO_TORAX', 'HALLAZGO_ANGIO', 'HALLAZGO_MACIZO']}, related_name='tomografias_hallazgos', to='pacientes.catalogo', verbose_name='Hallazgos'),
        ),
        migrations.CreateModel(
            name='Ecocardiograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(verbose_name='Fecha del estudio')),
                ('fevi', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FEVI (%)')),
                ('fevi_categoria', models.CharField(blank=True, choices=[('CONSERVADA', 'Conservada ≥ 50%'), ('LEVE', 'Levemente reducida 40-49%'), ('MODERADA', 'Moderadamente reducida 30-39%'), ('SEVERA', 'Severamente reducida < 30%')], max_length=20, verbose_name='Categoría FEVI')),
                ('tamaño_vd', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('LEVE', 'Dilatado leve'), ('MODERADO', 'Dilatado moderado'), ('SEVERO', 'Dilatado severo')], max_length=20, verbose_name='Tamaño VD')),
                ('tapse', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TAPSE (mm)')),
                ('funcion_vd_cualitativa', models.CharField(blank=True, choices=[('CONSERVADA', 'Conservada'), ('LEVE', 'Levemente disminuida'), ('MODERADA', 'Moderadamente disminuida'), ('SEVERA', 'Severamente disminuida')], max_length=20, verbose_name='Función VD')),
                ('paps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PAPs (mmHg)')),
                ('pad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PAD (mmHg)')),
                ('insuf_mitral', models.CharField(blank=True, choices=[('', '---'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], max_length=20, verbose_name='Insuficiencia mitral')),
                ('insuf_aortica', models.CharField(blank=True, choices=[('', '---'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], max_length=20, verbose_name='Insuficiencia aórtica')),
                ('velocidad_it', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Velocidad chorro IT (m/s)')),
                ('insuf_tricuspidea', models.CharField(blank=True, choices=[('', '---'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], max_length=20, verbose_name='Clasificación IT')),
                ('estenosis_aortica', models.CharField(blank=True, choices=[('', '---'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], max_length=20, verbose_name='Estenosis aórtica')),
                ('derrame_pericardico', models.CharField(blank=True, choices=[('', '---'), ('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('SEVERO', 'Severo')], max_length=20, verbose_name='Derrame pericárdico')),
                ('trombo_presente', models.BooleanField(default=False, verbose_name='Trombo intracavitario')),
                ('trombo_localizacion', models.CharField(blank=True, choices=[('AI', 'Aurícula izquierda'), ('VI', 'Ventrículo izquierdo'), ('AD', 'Aurícula derecha'), ('VD', 'Ventrículo derecho')], max_length=20, verbose_name='Localización del trombo')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecocardiogramas', to='pacientes.internacion')),
                ('signos_hp', models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'SIGNOS_HP'}, to='pacientes.catalogo', verbose_name='Signos de HP')),
            ],
            options={
                'verbose_name': 'Ecocardiograma',
                'verbose_name_plural': 'Ecocardiogramas',
                'ordering': ['-fecha'],
            },
        ),
    ]
