# Generated by Django 6.0.7 on 2026-08-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0037_alter_tomografia_hallazgos_ecocardiograma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocardiograma',
            name='signos_hp',
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='area_ad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Área de la aurícula derecha (cm²)'),
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='funcion_diastolica',
            field=models.CharField(blank=True, choices=[('', '---'), ('I', 'Grado I (disfunción diastólica leve)'), ('II', 'Grado II (disfunción diastólica moderada)'), ('III', 'Grado III (disfunción diastólica severa)')], max_length=10, verbose_name='Función diastólica'),
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='ivai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IVAI (ml/m²)'),
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='vci',
            field=models.CharField(blank=True, choices=[('', '---'), ('NORMAL', 'Normal'), ('DILATADA', 'Dilatada'), ('COLAPSO_MENOS_50', 'Colapso < 50%'), ('COLAPSO_MAS_50', 'Colapso > 50%')], max_length=20, verbose_name='Vena Cava Inferior (VCI)'),
        ),
        migrations.AlterField(
            model_name='ecocardiograma',
            name='internacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecocardiogramas', to='pacientes.internacion', verbose_name='Internación'),
        ),
    ]
