# Generated by Django 6.0.7 on 2026-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0038_remove_ecocardiograma_signos_hp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocardiograma',
            name='vci',
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='vci_colapso',
            field=models.CharField(blank=True, choices=[('', '---'), ('MENOS_50', 'Colapso < 50%'), ('MAS_50', 'Colapso > 50%')], max_length=20, verbose_name='VCI - Colapso'),
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='vci_tamano',
            field=models.CharField(blank=True, choices=[('', '---'), ('NORMAL', 'Normal'), ('DILATADA', 'Dilatada')], max_length=20, verbose_name='VCI - Tamaño'),
        ),
    ]
