# Generated by Django 6.0.7 on 2026-08-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0039_remove_ecocardiograma_vci_ecocardiograma_vci_colapso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibrobroncoscopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(verbose_name='Fecha del estudio')),
                ('bal_realizado', models.BooleanField(default=False, verbose_name='BAL realizado')),
                ('bal_resultado', models.TextField(blank=True, verbose_name='Resultado del BAL')),
                ('biopsia_realizada', models.BooleanField(default=False, verbose_name='Biopsia realizada')),
                ('biopsia_resultado', models.TextField(blank=True, verbose_name='Resultado de la biopsia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('hallazgos', models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'HALLAZGO_BRONCOSCOPICO'}, related_name='fibrobroncoscopias_hallazgos', to='pacientes.catalogo', verbose_name='Hallazgos')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibrobroncoscopias', to='pacientes.internacion', verbose_name='Internación')),
                ('procedimientos', models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'tipo__codigo': 'PROCEDIMIENTO_BRONCOSCOPICO'}, related_name='fibrobroncoscopias_procedimientos', to='pacientes.catalogo', verbose_name='Procedimientos realizados')),
            ],
            options={
                'verbose_name': 'Fibrobroncoscopia',
                'verbose_name_plural': 'Fibrobroncoscopias',
                'ordering': ['-fecha'],
            },
        ),
    ]
