# Generated by Django 6.0.7 on 2026-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0040_fibrobroncoscopia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocardiograma',
            name='tamaño_vd',
        ),
        migrations.AddField(
            model_name='ecocardiograma',
            name='tamano_vd',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('LEVE', 'Dilatado leve'), ('MODERADO', 'Dilatado moderado'), ('SEVERO', 'Dilatado severo')], max_length=20, verbose_name='Tamaño VD'),
        ),
    ]
